title: Sinclair TSANA
description: Data Scientist & Data analyst || Excel, R, Python, SQL
Exercer ma passion et mettre mes compétences
morales et pratiques au service des organisa-
tions afin de créer de la valeur et résoudre les
problèmes quotidiens.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
